"""add subscription plan and billing interval

Revision ID: 03806f7380c8
Revises: c33b76f3776a
Create Date: 2026-10-07 02:46:15.258467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03806f7380c8'
down_revision: Union[str, Sequence[str], None] = 'c33b76f3776a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('billing_interval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'billing_interval')
    op.drop_column('subscriptions', 'plan')
    # ### end Alembic commands ###
