"""add contract rollover date

Revision ID: c3daad3b213a
Revises: 473ee5676212
Create Date: 2026-08-30 05:01:36.621876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3daad3b213a'
down_revision: Union[str, Sequence[str], None] = '473ee5676212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('rollover_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'rollover_date')
    # ### end Alembic commands ###
