"""create contracts table

Revision ID: d26877ea359a
Revises: bc573cbc1aa8
Create Date: 2026-07-29 23:23:49.176867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26877ea359a'
down_revision: Union[str, Sequence[str], None] = 'bc573cbc1aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contract', sa.String(length=10), nullable=False),
    sa.Column('instrument', sa.String(length=10), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('first_trade_date', sa.Date(), nullable=True),
    sa.Column('last_trade_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('contract')
    )
    op.create_index('idx_contract_lookup', 'contracts', ['instrument', 'active', 'last_trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contract_lookup', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
