"""add days_to_maturity to contracts

Revision ID: ef97516ce7b4
Revises: d26877ea359a
Create Date: 2026-07-29 23:35:48.215878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef97516ce7b4'
down_revision: Union[str, Sequence[str], None] = 'd26877ea359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('days_to_maturity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'days_to_maturity')
    # ### end Alembic commands ###
