"""create candles table

Revision ID: f3cbdf1a3825
Revises: ef97516ce7b4
Create Date: 2026-08-01 14:51:00.292978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cbdf1a3825'
down_revision: Union[str, Sequence[str], None] = 'ef97516ce7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('instrument', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('timeframe', 'timestamp', 'contract')
    )
    op.create_index('idx_candles_contract', 'candles', ['contract', 'timeframe', 'timestamp'], unique=False)
    op.create_index('idx_candles_lookup', 'candles', ['instrument', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_instrument'), 'candles', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candles_instrument'), table_name='candles')
    op.drop_index('idx_candles_lookup', table_name='candles')
    op.drop_index('idx_candles_contract', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
